%  testingEx: A script showing how to use the provided code to test
%  % symmetries of Paley difference set ETFs.
%  % To compute the full vector and line automorphism groups, see
%  % https://github.com/jwiverson/frame-symmetries

% Author: Emily J King
% https://www.math.colostate.edu/~king/

% % % % % % % % % % % %
% % % % MODIFY AS NEEDED
p = 3; s = 3; 
% % % % % % % % % % % %
% % % % % % % % % % % %

% Load list of Paley difference set indices generated by PaleyDiffSet.ipynb
% % % % % % % % % % % %
% % % % MODIFY AS NEEDED
load('Paley_3_3.mat');   
PaleyDS = Paley_3_3; 
% % % % % % % % % % % %
% % % % % % % % % % % %

% Generate Paley difference set ETF and generators of the symmetries which
% % are not modulations
[PaleyETF,TGal,TCyc,matInds] = genPaleyETF(PaleyDS,p,s);

% If this is a blue field with one yellow entry per row/column, then TCyc
% % is a line automorphism 
figure, imagesc(abs((TCyc*PaleyETF)'*PaleyETF)), ...
    title('Testing if cyclic translation a line automorphism')

% If addtionally this is a blue field with one yellow entry per row/column,
% then TCyc is a vector automorphism 
figure, imagesc(real((TCyc*PaleyETF)'*PaleyETF)), ...
    title('Testing if cyclic translation a vector automorphism')


% If this is a blue field with one yellow entry per row/column, then TGal
% % is a line automorphism 
figure, imagesc(abs((TGal*PaleyETF)'*PaleyETF)), ...
    title('Testing if Galois permutation a line automorphism')


% If addtionally this is a blue field with one yellow entry per row/column,
% then TGal is a vector automorphism
figure, imagesc(real((TGal*PaleyETF)'*PaleyETF)), ...
    title('Testing if Galois permutation a vector automorphism')
